title: PaddleLabel
description: An effective and flexible tool for data annotation
theme: just-the-docs

url: https://paddlecv-sig.github.io/
baseurl: "/PaddleLabel/CN/"

permalink: pretty

search_enabled: false
heading_anchors: true
enable_copy_code_button: true

aux_links: # remove if you don't want this link to appear on your pages
  项目 Github: https://github.com/PaddleCV-SIG/PaddleLabel

plugins:
  - jemoji

kramdown:
  parse_block_html: true
  # syntax_highlighter_opts:
  #   block:
  #     line_numbers: true
